environment:
  matrix:
    # We don't actually use the Travis Python, but this keeps it organized.
    - PYTHON_VERSION: "2.7"
      MPL_VERSION: "1.4"
    - PYTHON_VERSION: "3.4"
      MPL_VERSION: "1.4"
    - PYTHON_VERSION: "3.5"
      MPL_VERSION: "1.4"
    - PYTHON_VERSION: "2.7"
      MPL_VERSION: "1.5"
    - PYTHON_VERSION: "3.4"
      MPL_VERSION: "1.5"
    - PYTHON_VERSION: "3.5"
      MPL_VERSION: "1.5"
install:
  # We do this conditionally because it saves us some downloading if the
  # version is the same.
  - set PATH=C:\Miniconda3;C:\Miniconda3\Scripts;%PATH%
  # make sure we use an 'innocent' default matplotlib environment
  - cmd: touch matplotlibrc
  - conda config --set always_yes yes --set changeps1 no
  # Useful for debugging any issues with conda
  - conda info -a
  - set ENVKEY=py%PYTHON_VERSION%_mpl%MPL_VERSION%
  - conda env create -f tests/envs/environment_%ENVKEY%.yml
  - source activate psyplot_%ENVKEY%
  - pip install coveralls
  # install the test plugin
  - cd tests/test_plugin
  - python setup.py install
  - cd ../../
  - python setup.py install
  # export the environment for debugging
  - conda env export -n psyplot_%ENVKEY%

script:
  - python setup.py pytest
