name: psyplot
channels:
    - chilipp
    - scitools
dependencies:
    - psyplot
    - dask
    - xarray
    - netCDF4
    - matplotlib
    - cartopy
    - gdal
    - seaborn
    - ipython
    - nbconvert
