name: psyplot
channels:
    - chilipp
    - scitools
dependencies:
    - psyplot
    - dask
    - xarray
    - bottleneck
    - netCDF4
    - matplotlib
    - cartopy
    - seaborn
    - ipython
    - nbconvert
