name: psyplot_docs
dependencies:
    - python=3.5
    - dask
    - xarray
    - netCDF4
    - matplotlib
    - seaborn
    - ipython
    - sphinx
    - pip:
        - sphinx-argparse
        - autodocsumm
        - cdo
