name: psyplot_docs
channels:
    - chilipp
    - scitools
dependencies:
    - python=3.4
    - psyplot
    - dask
    - xarray
    - netCDF4
    - matplotlib
    - cartopy
    - seaborn
    - ipython
    - nbconvert
    - ipykernel
    - pip:
        - sphinx-argparse

