name: psyplot
channels:
    - chilipp
    - scitools
dependencies:
    - psyplot
    - dask
    - xarray
    - matplotlib
    - cartopy
    - gdal
    - ipython
    - seaborn
    - sphinx=1.3.1
    - IPython
    - nbconvert
    - jupyter
