name: psyplot
channels:
    - chilipp
    - scitools
dependencies:
    - psyplot
    - dask
    - xarray
    - matplotlib
    - cartopy
    - gdal
    - ipython
    - seaborn
    - sphinx
    - IPython
    - nbconvert
    - jupyter
