name: psyplot
channels:
    - chilipp
    - scitools
dependencies:
    - psyplot_gui
    - dask
    - xarray
    - netCDF4
    - cartopy
    - seaborn
    - bottleneck
    - qtconsole
    - ipykernel
    - pexpect
    - pygments
    - sphinx
    - pip:
        - fasteners
        - cyordereddict
